### ISSUE TITLE
Roadmap to 2.0.0

### ISSUE THREAD

**Issue by Galadirith** [Galadirith/markdown-preview-plus#51]
## 1.7.0 (2015-08-09)

They all seem to be for @leipert :+1: 

- [x] #49: Fix caching of images.
- [x] #50: Location of csl and bib files
- [x] #48: Add doc for pandoc options
- [x] #46: Add doc for possibilities of latex

## 2.0.0 (2015-08-30)

They seem to be for @leipert:

- [x] #47: Migrate to markdown-it, which may fix #20, #17 and #7 
- [x] #54: Macro extension #14 should work with pandoc

They seem to be for @Galadirith 

- [x] #9: Sync between scroll and src
- [x] #14: Merge macros

**Comment by Galadirith** [comment]
@leipert Thanks so much for all the time you've spent on issues over the last couple of weeks.

I wanted to focus my loss of concentration by fixing down dates and issues/features that we can work on and roll out over the next month. By thought were that we could aim for a `1.7.0` release by this Sunday (9.8.15) which can include any minor fixes, documentation updates etc.

Then we can work towards a `2.0.0` release for 2 weeks after that on Friday (21.8.15). In that the main focus is of course migrating to `markdown-it` and generally bringing much more stability to MPP.

What do you think of that timeline?

If you happy with the timeline then we can populate the stub at the top of this issue; we have the milestone labels, however they don't have any facility to discuss them collectivity so we could do that here. I hope that you can also edit the stub, but if not we could move that to a wiki page.

Let me know your thoughts, thanks @leipert

**Comment by leipert** [comment]
Sounds good to me, I added the dates to the milestones and updated your first entry in this issue.

Doesn't scroll sync depend on markdown-it?

**Comment by leipert** [comment]
@Galadirith I really "refactored" the readme and documentation, please have a look whether you like it.

**Comment by Galadirith** [comment]
@leipert you are a :star2:

> Doesn't scroll sync depend on markdown-it?

It does, but I can and have been working on the code independent of MPP so it won't be an issue to splice that code into MPP when markdown-it is integrated.

>  I really "refactored" the readme and documentation, please have a look whether you like it.

It looks absolutely fantastic, I really love the modularisation. There were a couple of things I've changed in 88100d6 but your refactor is fantastic :D

**Comment by Galadirith** [comment]
@leipert Just to let know you I won't have access to a computer for most of Saturday. We can definitely make sure the image caching fix is stable, and if your happy with your CI branch merge that in (I don't have any experience with CI so I'll follow your lead on that). 

I would be happy for anything else not complete to be bumped to 2.0.0 but let me know thoughts :D

**Comment by Galadirith** [comment]
@leipert Any amount of thanks and gratitude really would fall far short of what all your long and hard work this weekend deserves, but never the less thank you. Two weeks until 2.0.0 :D

**Comment by Galadirith** [comment]
@leipert Sorry for the silence today. I've been working on our sync feature which threw up quite a few challenges with the integration, which I should have realised was inevitable :D

I noticed as well I had originally said we'll be pushing out `2.0.0` today! I have been working assuming it was Sunday like for `1.7.0` which was my mistake but are you happy to release on Sunday?

One final thing, I'll be a physics conference next week and will be leaving Sunday afternoon. I should have internet that evening and throughout the week but I can't guarantee it so I would you be happy with a Sunday morning release?

**Comment by Galadirith** [comment]
I have revised the expect ship date for `2.0.0` to this coming Sunday, 30.08.15. I really apologise for the delay, and thanks for being so patient :D

**Comment by leipert** [comment]
@Galadirith Sorry for the silence on my part. Everything looks fine so far, also the source sync.

**Comment by Galadirith** [comment]
@leipert No problem at all. Thanks for checking out syncing. I've just pushed a few bug fixes to #80 and will be uploading the specs shortly. It'll be a busy day but I'm confident every milestone for `2.0.0` can be shipped today (or at the very least in the early hours of tomorrow morning :D)

**Comment by Galadirith** [comment]
@leipert I will be away from a computer today, so if you do have an opportunity to populate the changelog I'll make sure to publish `2.0.0` when i'm back this evening :D

**Comment by leipert** [comment]
@Galadirith Sorry. We didn't talk right to each other. My fancy Changelog Program needs the tag to exist, to create the changelog right. Otherwise it shows [`Unreleased`](https://github.com/Galadirith/markdown-preview-plus/commit/eb7916e6eb3ddb694990d8f63a1ec73e7860c12f#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3) instead of the version tag.

Just release the hounds (and 2.0.0) and I will update the CHANGELOG.

**Comment by leipert** [comment]
By the way, my "fancy" Changelog Program is: https://skywinder.github.io/github-changelog-generator/

**Comment by Galadirith** [comment]
@leipert Ahhh, no thats no problem my fault for not clarifying, and when I think about it it doesn't make sense to add a changelog for a release that doesn't exist in any case.

I'll just add a quick addition to features for on demand syncing (which I omitted) and push the release, get ready :D

**Comment by leipert** [comment]
One Test fails mysteriously in Travis [[link]](https://travis-ci.org/Galadirith/markdown-preview-plus/builds/78317410). As it does not fail locally or on the other CIs, I just deactivated it for the 2.0.0 release.

It seems like there is a timing problem. Or something. Will write an issue for v2.0.0 to investigate the problem ;)

**Comment by Galadirith** [comment]
Mmm interesting. I have in the last week had Travis test fail, and then if I restarted the build they would pass? I should have recorded the errors.

**Comment by leipert** [comment]
Wrote the issue #84. Is for 2.1.0 of course.

Release - Release - Release :chart_with_upwards_trend:

**Comment by Galadirith** [comment]
Its done :D
